---
- name: Restart Gitea
  service:
      name: gitea
      state: restarted
  when: ansible_service_mgr == "systemd"

- name: Reload systemd
  systemd:
      daemon_reload: true
  when: ansible_service_mgr == "systemd"
