- name: Download java jdk 8 oracle
  hosts: servers
  vars:
    java_download: https://direct.gdrive.vip/1C-oX7VDEC2AvOcuIsArn6atqHrHiK8ue
    download_folder: /usr/lib/jvm
    java_tar_file: jdk-8u212-linux-x64.tar.gz
    java_tar_name: jdk1.8.0_212
    java_dir_name: java-8-oracle

  tasks:
    - name: Make jvm directory
      file:
        path: '{{download_folder}}'
        state: directory
        mode: '0755'
      become: true
      
    - name: Download Oracle Jdk
      get_url: 
        url: '{{java_download}}'
        dest: '{{download_folder}}/{{java_tar_file}}'
      become: true
      become_user: root

    - name: Java unarchive, extract file
      unarchive:
        src: '{{download_folder}}/{{java_tar_file}}'
        dest: '{{download_folder}}'
      become: true

    - name: Rename java_tar_name in java_dir_name
      command: 'mv {{download_folder}}/{{java_tar_name}} {{download_folder}}/{{java_dir_name}}'
      become: true


