- name: Download java jdk 7 oracle
  hosts: servers
  vars:
    java_download: http://mirrors.iyunwei.com/tomcat/jdk-7u79-linux-x64.tar.gz
    download_folder: /opt
    java_file: jdk-7u79-linux-x64.tar.gz
    java_name: java-7-oracle


  tasks:
    - name: Make jvm directory
      file:
        path: /usr/lib/jvm
        state: directory
        mode: '0755'
      
    - name: Download Oracle Jdk
      get_url: 
        url: '{{java_download}}'
        dest: '{{download_folder}}'

    - name: Java unarchive, extract file
      unarchive:
        src: '{{download_folder}}/{{java_file}}'
        dest: /usr/lib/jvm/

    - name: Rename java directory
      command: 'mv /usr/lib/jvm/jdk1.7.0_79 /usr/lib/jvm/{{java_name}}'
